import Head from "next/head";
import Header from "./header";
import Hero from "./hero";
import History from "./history";
import Climb from "./climb";
import Footer from "./footer";

export default function Home() {
    return (
        <div>
            <Head>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta charSet="UTF-8" />
                <meta http-Equiv="X-UA-Compatible" content="IE=edge" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1.0"
                />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link
                    rel="preconnect"
                    href="https://fonts.gstatic.com"
                    crossOrigin="true"
                />
                <link
                    rel="shortcut icon"
                    href="./images/logo.png"
                    type="image/x-icon"
                />
                <title>LA Mountains</title>
            </Head>
            <Header />
            <Hero />
            <History />
            <Climb />
            <Footer />
        </div>
    );
}
